# Generated by Django 3.2.25 on 2024-05-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="core.Ingredient"),
        ),
    ]
